pipeline {
    agent any

    stages {
        // stage('Checkout') {
        //     steps {
        //       git credentialsId: "${env.GITHUB_CREDS}", url: "${env.GITHUB_REPO}"
        //     }
        // }
        stage('Build') {
            steps {
                dir('client') {
                    sh '''
                        pwd
                        npm install
                        npm run build
                    '''
                }
            }
        }
    }
}
