pipeline {
    agent any
    
    environment {
        PATH_CLIENT = "client"
        USERNAME = "hgthaii"
        DOCKER_IMAGE_NAME = "client"
        NODE_VERSION = "14.21.2"
    }
    
    stages {
        stage("Clone") {
            steps {
                echo "Cloning source from Git repository"
                git "https://github.com/hgthaii/finder.git"
            }
        }
        
        stage("Build") {
            steps {
                dir("${PATH_CLIENT}") {
                    echo "Installing dependencies"
                    bat "npm install"
                    
                    echo "Building the React app"
                    bat "react-scripts build"
                }
            }
        }
        
        stage("Test") {
            steps {
                dir("${PATH_CLIENT}") {
                    echo "Running tests"
                    bat "npm run format"
                }
            }
        }
        
        stage("Docker Build and Push") {
            steps {
                dir("${PATH_CLIENT}") {
                    echo "Build docker image"
                    bat "docker build -t ${USERNAME}/${DOCKER_IMAGE_NAME} ."
                    bat "docker login -u ${USERNAME} -p thajlh123"
                    echo "Pubat image lên Dockerhub"
                    bat "docker push ${USERNAME}/${DOCKER_IMAGE_NAME}:latest"
                }
            }
        }
    }
    
    post {
        success {
            echo "Build successful!"
        }
        
        failure {
            echo "Build failed!"
        }
    }
}
