pipeline {
    agent any

    environment {
        PATH_SERVER = "server"
        DOCKER_REGISTRY_URL = "hgthaii/server:latest"
        DOCKER_IMAGE_NAME = "server"
        NODE_VERSION = "14.21.2"
    }

    stages {
        stage("Checkout") {
            steps {
                echo "Clone source về Jenkins"
                git "https://github.com/hgthaii/finder.git"
            }
        }

        stage("Build") {
            steps {
                dir("${PATH_SERVER}") {
                    sh "npm install node@${NODE_VERSION}"
                    sh "npm install"
                    sh "npm run format"
                }
            }
        }
        stage("Test") {
            steps {
                sh "node -v"
                sh "npm -v"
            }
        }
        stage("Build and push Docker image") {
            steps {
                dir("${PATH_SERVER}") {
                    echo "Build docker image"
                    sh "docker build -t ${DOCKER_REGISTRY_URL} ."
                    echo "Push image lên Dockerhub"
                    sh "docker push ${DOCKER_REGISTRY_URL}"
                }
            }
        }
    }

    post {
        success {
            sh """
    curl -X POST \
     -H "Content-Type: application/json" \
     -d "{"chat_id": "${USERID}", "text": " \ud83d\udc4d \ud83d\udc4d \ud83d\udc4d \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: SUCCESS \nCommit: ${GIT_COMMIT} ", "disable_notification": true}" \
     ${WEBHOOK_URL}
            """   
    }

        failure {
        sh """
    curl -X POST \
     -H "Content-Type: application/json" \
     -d "{"chat_id": "${USERID}", "text": " \ud83d\ude21 \ud83d\ude21 \ud83d\ude21 \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: FAILURE \nStage: ${FAILED_STAGE} \nCommit: ${GIT_COMMIT} ", "disable_notification": true}" \
     ${WEBHOOK_URL}
        """
        }

        aborted {
        sh """
    curl -X POST \
     -H "Content-Type: application/json" \
     -d "{"chat_id": "${USERID}", "text": " \u2620\ufe0f \u2620\ufe0f \u2620\ufe0f \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: ABORTED \nStage: ${FAILED_STAGE} \nCommit: ${GIT_COMMIT} ", "disable_notification": true}" \
     ${WEBHOOK_URL}
        """
        }

        unstable {
        sh """
    curl -X POST \
     -H "Content-Type: application/json" \
     -d "{"chat_id": "${USERID}", "text": " \ud83d\ude4a \ud83d\ude4a \ud83d\ude4a \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: UNSTABLE \nStage: ${FAILED_STAGE} \nCommit: ${GIT_COMMIT} ", "disable_notification": true}" \
     ${WEBHOOK_URL}
        """
        }

        always {
            deleteDir()
        }


}
}
