pipeline {
    agent any

    environment {
        PATH_SERVER = "server"
        USERNAME = "hgthaii"
        DOCKER_REGISTRY_URL = "hgthaii/server:latest"
        DOCKER_IMAGE_NAME = "server"
        NODE_VERSION = "14.21.2"
    }

    stages {
        stage("Checkout") {
            steps {
                echo "Clone source về Jenkins"
                git "https://github.com/hgthaii/finder.git"
            }
        }

        stage("Build") {
            steps {
                dir("${PATH_SERVER}") {
                    bat "npm install node@${NODE_VERSION}"
                    bat "npm install"
                    bat "npm run format"
                }
            }
        }

        stage("Test") {
            steps {
                bat "node -v"
                bat "npm -v"
            }
        }

        stage("Build and push Docker image") {
            // agent {
            //     docker { image "${DOCKER_REGISTRY_URL}"}
            // }
            steps {
                dir("${PATH_SERVER}") {
                    echo "Build docker image"
                    bat "docker build -t ${USERNAME}/${DOCKER_IMAGE_NAME} ."
                    bat "docker login -u ${USERNAME} -p thajlh123"
                    echo "Push image lên Dockerhub"
                    bat "docker push ${USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
                }
            }
        }
    }
}
